---
name: "Code Quality: Terraform"

on:
  pull_request:
  push:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    strategy:
      # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
      fail-fast: false
      matrix:
        workspaces:
          - "./examples/basic"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false
          terraform_version: ${{ secrets.TERRAFORM_VERSION }}

      - name: Format Terraform code for Module
        run: terraform fmt -check -recursive
        env:
          working-dir: "./"

      - name: Initialize Terraform for Examples
        run: terraform init
        env:
          working-dir: "${{ matrix.workspaces }}"

      - name: Format Terraform code for Examples
        run: terraform fmt -check -recursive
        env:
          working-dir: "${{ matrix.terraform_directories }}"

      - name: Validate Terraform code for examples
        run: terraform validate
        env:
          working-dir: "${{ matrix.terraform_directories }}"
